### ISSUE TITLE
Create Function Based Components

### ISSUE THREAD

**Issue by aniruddhabagal** [aniruddhabagal/monsters-rolodex#1]
- [ ] Transform Class Based Components to Function Based Components
- [ ] Design and transform the website

**Comment by uttampandit** [comment]
Hi @aniruddhabagal I would like to work on the tasks you want, Can you assign me so that i can start working on it?

**Comment by aniruddhabagal** [comment]
> Hi @aniruddhabagal I would like to work on the tasks you want, Can you assign me so that i can start working on it?

Hi @uttampandit
Sure you can 1st star the repo and fork it, create a branch, make changes and create a pr .

**Comment by uttampandit** [comment]
Can you just assign me, so that I could start working on it.
