### ISSUE TITLE
Optimization: I want to make this app responsive

### ISSUE THREAD

**Issue by ShahrozAhmd** [aniruddhabagal/monsters-rolodex#8]
The app is very interesting but not responsive on all devices, kindly assign this issue to me so I  can make the website responsive for all devices.

**Comment by ShahrozAhmd** [comment]
Hey 👋  @aniruddhabagal  kindly assign this issue to me , thanks alot

**Comment by aniruddhabagal** [comment]
Hi, @ShahrozAhmd Thank you for pointing this out.
I have assigned this issue to you. :)

**Comment by ShahrozAhmd** [comment]
Thanks @aniruddhabagal 👍
